version: "3"

services:
  mongo:
    hostname: mongo_local
    container_name: mongo
    image: mongo:5.0
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ${DOCKER_ENV_PATH}/mongodb/db:/data/db
      - ${DOCKER_ENV_PATH}/mongodb/dump:/dump
