version: "3"

services:
  mongo:
    hostname: mongo_local
    container_name: mongo
    image: mongo:4.2
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ${SO_DOCKER_PATH}/mongodb:/data/db
