version: "3"

services:
  mysql:
    hostname: mysql_local
    container_name: mysql
    image: mysql:8.0.29-oracle
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ${SO_DOCKER_PATH}/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "default"
      MYSQL_ROOT_PASSWORD: "admin"
