version: "3"

services:
  postgres:
    hostname: postgres_local
    container_name: postgres
    image: postgres:10.1
    restart: always
    ports:
      - 5432:5432
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_DB: "default"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    volumes:
      - ${LEFT_DOCKER_PATH}/postgresql:/var/lib/postgresql
      - ${LEFT_DOCKER_PATH}/postgresql/data:/var/lib/postgresql/data
