version: "3"

services:
  rabbitmq:
    hostname: rabbitmq_local
    container_name: rabbitmq
    image: rabbitmq:3.8.9-management
    restart: always
    ports:
      - 15672:15672
      - 5672:5672
      - 25676:25676
